---

spring:
  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: create

  output:
    ansi:
      enabled: always
  instancio:
    bean:
      validation:
        enabled: true
  sql:
    init:
      mode: always
  profiles:
    default: development

logging:
  level:
    root: INFO

api-key: "YOUR_API_KEY"
translate-url: "https://translate.api.cloud.yandex.net/translate/v2/translate"
api-url: "https://translate.api.cloud.yandex.net/translate/v2/languages"
